export const CREATE_SUPPLIES_REQUEST = "CREATE_SUPPLIES_REQUEST";
export const CREATE_SUPPLIES_SUCCESS = "CREATE_SUPPLIES_SUCCESS";
export const CREATE_SUPPLIES_FAIL = "CREATE_SUPPLIES_FAIL";
export const CREATE_SUPPLIES_RESET = "CREATE_SUPPLIES_RESET";

export const GET_SUPPLIES_REQUEST = "GET_SUPPLIES_REQUEST";
export const GET_SUPPLIES_SUCCESS = "GET_SUPPLIES_SUCCESS";
export const GET_SUPPLIES_FAIL = "GET_SUPPLIES_FAIL";

export const DELETE_SUPPLIES_SUCCESS = "DELETE_SUPPLIES_SUCCESS";
export const DELETE_SUPPLIES_FAIL = "DELETE_SUPPLIES_FAIL";
export const DELETE_SUPPLIES_RESET = "DELETE_SUPPLIES_RESET";

export const APPROVE_SUPPLIES_SUCCESS = "APPROVE_SUPPLIES_SUCCESS";
export const APPROVE_SUPPLIES_FAIL = "APPROVE_SUPPLIES_FAIL";
export const APPROVE_SUPPLIES_RESET = "APPROVE_SUPPLIES_RESET";

export const DELETE_REQUEST_SUCCESS = "DELETE_REQUEST_SUCCESS";
export const DELETE_REQUEST_FAIL = "DELETE_REQUEST_FAIL";
export const DELETE_REQUEST_RESET = "DELETE_REQUEST_RESET";

export const UPDATE_SUPPLIES_REQUEST = "UPDATE_SUPPLIES_REQUEST";
export const UPDATE_SUPPLIES_SUCCESS = "UPDATE_SUPPLIES_SUCCESS";
export const UPDATE_SUPPLIES_FAIL = "UPDATE_SUPPLIES_FAIL";
export const UPDATE_SUPPLIES_RESET = "UPDATE_SUPPLIES_RESET";

export const CREATE_REQUEST_SUPPLIES_REQUEST =
  "CREATE_REQUEST_SUPPLIES_REQUEST";
export const CREATE_REQUEST_SUPPLIES_SUCCESS =
  "CREATE_REQUEST_SUPPLIES_SUCCESS";
export const CREATE_REQUEST_SUPPLIES_FAIL = "CREATE_REQUEST_SUPPLIES_FAIL";
export const CREATE_REQUEST_SUPPLIES_RESET = "CREATE_REQUEST_SUPPLIES_RESET";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
